# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog by Intrainos
email: blog@intrainos.net
description: > A Blog by Intrainos using jekyll and github-pahes. Built with <3
baseurl: ""
url: "http://blog.intrainos.net" # the base hostname & protocol for your site
twitter_username: intrainos
github_username:  intrainos

# Build settings
markdown: kramdown
